### ISSUE TITLE
Fatal Error Fatal error: Uncaught Error: Class "ZipArchive" not found in C:\xampp\htdocs\www\roadmap.php:181 Stack trace: #0

### ISSUE THREAD

**Issue by breimann** [ktrue/proclaim-utility#1]
Hi there, our church has recently moved from PowerPoint to Proclaim and my job is to create a service order/roadmap to print for those with low vision, and for the sound/data/band members.

I came across your utility, and finally got xxampp installed and managed to run "make-roadmap.php". I uploaded a backed up proclaim presentation to test as a .prs file and got this error...

_Fatal error: Uncaught Error: Class "ZipArchive" not found in C:\xampp\htdocs\www\roadmap.php:181 Stack trace: #0 {main} thrown in C:\xampp\htdocs\www\roadmap.php on line 181_

Here is a screen shot:
![2023-02-08](https://user-images.githubusercontent.com/24246478/217396730-ecf31eee-75b1-498f-b5fa-50b1e74362d1.png)

Im really not sure what i'm doing, so any assistance would be greatly appreciated!

**Comment by ktrue** [comment]
With XAMPP, you will need to edit the \xampp\php\php.ini to enable some extensions.
Here's my current extensions section:
```
extension=bz2
extension=curl
;extension=ffi
;extension=ftp
extension=fileinfo
extension=gd
extension=gettext
;extension=gmp
extension=intl
;extension=imap
;extension=ldap
extension=mbstring
extension=exif      ; Must be after mbstring as it depends on it
extension=mysqli
;extension=oci8_12c  ; Use with Oracle Database 12c Instant Client
;extension=oci8_19  ; Use with Oracle Database 19 Instant Client
;extension=odbc
;extension=openssl
;extension=pdo_firebird
extension=pdo_mysql
;extension=pdo_oci
;extension=pdo_odbc
;extension=pdo_pgsql
extension=pdo_sqlite
;extension=pgsql
;extension=shmop

; The MIBS data available in the PHP distribution must be installed.
; See https://www.php.net/manual/en/snmp.installation.php
;extension=snmp

;extension=soap
;extension=sockets
;extension=sodium
;extension=sqlite3
;extension=tidy
;extension=xsl

;zend_extension=opcache
```
I think the critical one for Zip is
```
extension=bz2
```

After you change the php.ini and save it, restart Apache using the control panel, then doe the make-roadmap.php again.  That should fix it.

**Comment by breimann** [comment]
Thankyou for your prompt response ktrue.

I'll try this and let you know how I go.

**Comment by breimann** [comment]
Hi Ktrue, unfortunately this didn't fix it.

I copied and pasted your extensions post into my php.ini, but I noticed I already had extension=bz2 enabled before that.

Any other ideas?

**Comment by ktrue** [comment]
Try doing a phpinfo() on a page.  It should show something like this:

![2023-02-07_ZipPHP](https://user-images.githubusercontent.com/17507343/217425194-bba59ed1-d831-44f7-a389-296f93f443a0.jpg)

**Comment by ktrue** [comment]
BTW.. the ZipArchive class has been in PHP for quite a while (PHP 5 >= 5.2.0, PHP 7, PHP 8, PECL zip >= 1.1.0)

As of PHP 7.4.0, in order to use these functions you must compile PHP with zip support by using the `--with-zip` configure option. Is it possible your PHP was compiled without this option?

**Comment by breimann** [comment]
Hi Ktrue,

I've done a phpinfo() and saved the page from in chrome as a pdf, i can see a ZLIB section, but not a ZIP section as in your screen shot...

breimann

[PHP 8.2.0 - phpinfo().pdf](https://github.com/ktrue/proclaim-utility/files/10681664/PHP.8.2.0.-.phpinfo.pdf)

**Comment by breimann** [comment]
It is possible PHP was configured without that option for sure, i just used the defaults when i installed xxampp...

**Comment by ktrue** [comment]
I'm using XAMPP with PHP Version 8.1.2 and it has Zip included.  You're using PHP Version 8.2.0 .. maybe back up a version from Apachefriends and try again?

**Comment by ktrue** [comment]
I'm running PHP 8.2.0 on my Dreamhost site and the scripts work fine.. so it looks like your XAMPP needs to downgrade to a prior PHP 8.1 version.  They must have neglected to get Zip included in the configuration :(

**Comment by breimann** [comment]
Ok, i'll need to look into how to do that in a day or two, i'm working in the church office tomorrow!
Thanks again for all your time and help, really appreciate it.

**Comment by ktrue** [comment]
I installed XAMPP 8.0.2 on a test system.  I see the default is to not enable the Zip extension.

Change php.ini from `;extension=zip` to `extension=zip` and restart Apache.  The Zip extension will be enabled and the Proclaim scripts should work correctly.

**Comment by breimann** [comment]
Yay!!!! That fixed it. I also installed the xxampp 8.0.25 version on the computer at church, and enabled that extension in php.ini and i have a roadmap!!! Wow, this will save HOURS of time, thankyou so much, and thankyou Father God for you and your team!

**Comment by ktrue** [comment]
I'm glad you've found the software useful for your church -- it provides the worship roadmaps for us and makes it very easy to just create the Proclaim slides and have individualized parts for all the worship participants.  Blessings to you!
